"""
Distribute generated auton files into the VEX project tree.

    python interpreter/install.py

Copies botlang/target/*.cpp to override/src/autons/, *.hpp to
override/include/autons/, and (re)generates override/include/autons.hpp
as the aggregator header that main.cpp can include to get every
bot::autonomous::* function declaration.

Only touches files marked with the GENERATED_MARKER — hand-written files
in src/autons/ or include/autons/ are never deleted.
"""

import sys
from pathlib import Path


GENERATED_MARKER = "// GENERATED BY BOTLANG — do not edit by hand"


def project_root() -> Path:
    # interpreter/install.py lives at <project>/botlang/interpreter/install.py
    return Path(__file__).resolve().parents[2]


def is_generated(p: Path) -> bool:
    try:
        with p.open("r", encoding="utf-8") as f:
            head = f.read(200)
        return GENERATED_MARKER in head
    except OSError:
        return False


def clean_generated(directory: Path) -> int:
    if not directory.exists():
        return 0
    removed = 0
    for f in directory.iterdir():
        if f.is_file() and is_generated(f):
            f.unlink()
            removed += 1
    return removed


def copy_pair(target_dir: Path, src_dir: Path, inc_dir: Path) -> list[str]:
    """Copy each generated .cpp + .hpp pair from target/ into src/autons/
    and include/autons/. Returns a sorted list of auton names installed."""
    names: list[str] = []
    for cpp in sorted(target_dir.glob("*.cpp")):
        name = cpp.stem
        hpp = cpp.with_suffix(".hpp")
        if not hpp.exists():
            print(f"  ! skipping {name}: .hpp is missing (run main.py first?)")
            continue
        (src_dir / cpp.name).write_text(cpp.read_text(encoding="utf-8"), encoding="utf-8")
        (inc_dir / hpp.name).write_text(hpp.read_text(encoding="utf-8"), encoding="utf-8")
        names.append(name)
        print(f"  installed {name}  (src/autons/{name}.cpp, include/autons/{name}.hpp)")
    return names


def write_aggregator(aggregator_path: Path, names: list[str]) -> None:
    lines = [
        GENERATED_MARKER,
        "// Aggregator header — #include this from main.cpp to get every",
        "// bot::autonomous::* function declaration.",
        "#pragma once",
        "",
    ]
    for name in names:
        lines.append(f'#include "autons/{name}.hpp"')
    if not names:
        lines.append("// (no auton routines have been compiled yet)")
    aggregator_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    root = project_root()
    target_dir = root / "botlang" / "target"
    src_dir = root / "src" / "autons"
    inc_dir = root / "include" / "autons"
    aggregator = root / "include" / "autons.hpp"

    if not target_dir.exists():
        print(f"error: {target_dir} does not exist — run main.py first")
        return 1

    src_dir.mkdir(parents=True, exist_ok=True)
    inc_dir.mkdir(parents=True, exist_ok=True)

    removed_src = clean_generated(src_dir)
    removed_inc = clean_generated(inc_dir)
    if removed_src or removed_inc:
        print(f"cleaned {removed_src + removed_inc} stale generated files")

    names = copy_pair(target_dir, src_dir, inc_dir)
    write_aggregator(aggregator, names)
    print(f"wrote {aggregator.relative_to(root)}  ({len(names)} auton{'' if len(names)==1 else 's'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
