"""
Bot language CLI.

    python interpreter/main.py autons/skills.bot

Compiles the .bot source into a C++ header + implementation pair under
botlang/target/. To distribute them into src/autons/ and include/autons/,
run install.py afterwards.

One .bot file becomes one auton routine:

    autons/skills.bot   ──►   target/skills.hpp + target/skills.cpp
                                                     │
                                                     └──►  bot::autonomous::skills()
"""

import sys
from pathlib import Path

from tokenizer import tokenize, TokenizeError
from config import load_config
from matcher import transpile


GENERATED_MARKER = "// GENERATED BY BOTLANG — do not edit by hand"

HPP_TEMPLATE = """\
{marker}
// source: {source_rel}
#pragma once

namespace bot {{
namespace autonomous {{

void {name}();

}}  // namespace autonomous
}}  // namespace bot
"""

CPP_TEMPLATE = """\
{marker}
// source: {source_rel}
#include "autons/{name}.hpp"
#include "bot/bot.hpp"

namespace bot {{
namespace autonomous {{

void {name}() {{
{body}
}}

}}  // namespace autonomous
}}  // namespace bot
"""


def find_config(start: Path) -> Path | None:
    for d in [start.parent, *start.parent.parents]:
        candidate = d / "language.bot"
        if candidate.exists():
            return candidate
    return None


def indent_body(body: str, spaces: int = 4) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else "" for line in body.split("\n"))


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("usage: python main.py <file.bot>")
        return 1

    src_file = Path(argv[1]).resolve()
    if not src_file.exists():
        print(f"error: {src_file} does not exist")
        return 1
    if src_file.suffix != ".bot":
        print(f"error: expected a .bot file, got {src_file.name}")
        return 1

    config_file = find_config(src_file)
    if config_file is None:
        print("error: no language.bot found walking up from the source file")
        return 1

    name = src_file.stem
    if not (name.replace("_", "").isalnum() and not name[0].isdigit()):
        print(f"error: {name!r} is not a valid C++ identifier — rename the .bot file")
        return 1

    try:
        tokens = tokenize(src_file.read_text(encoding="utf-8"))
    except TokenizeError as e:
        print(f"tokenize error in {src_file.name}: {e}")
        return 1

    config = load_config(config_file.read_text(encoding="utf-8"))
    body = transpile(tokens, config)

    try:
        source_rel = src_file.relative_to(config_file.parent).as_posix()
    except ValueError:
        source_rel = src_file.name

    hpp_text = HPP_TEMPLATE.format(marker=GENERATED_MARKER, source_rel=source_rel, name=name)
    cpp_text = CPP_TEMPLATE.format(
        marker=GENERATED_MARKER,
        source_rel=source_rel,
        name=name,
        body=indent_body(body, 4),
    )

    out_dir = config_file.parent / "target"
    out_dir.mkdir(exist_ok=True)
    hpp_out = out_dir / f"{name}.hpp"
    cpp_out = out_dir / f"{name}.cpp"
    hpp_out.write_text(hpp_text, encoding="utf-8")
    cpp_out.write_text(cpp_text, encoding="utf-8")

    base = config_file.parent
    print(f"wrote {hpp_out.relative_to(base)}")
    print(f"wrote {cpp_out.relative_to(base)}")
    print("next: python interpreter/install.py")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
